name: libcimbar_example
description: Example app for the libcimbar Flutter plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  libcimbar:
    path: ../
  hotkey_manager: ^0.2.3
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  image: ^4.1.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
