name: example_decode
description: libcimbar Web/Android decoder app.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  libcimbar:
    path: ../
  camera: ^0.11.0+2
  path_provider: ^2.1.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
